; PlatformIO Project Configuration File
;
; ESP32-C3 SuperMini boards are compatible with the ESP32-C3-DevKitM-1
; PlatformIO board definition.

[env:esp32-c3-supermini]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
